export type MenuTag =
  | "popular"
  | "new"
  | "spicy"
  | "vegetarian"
  | "alcoholic"
  | "non-alcoholic";

export type MenuItem = {
  slug: string;
  name: string;
  description?: string;
  price: number | string;
  image?: string;
  isAvailable: boolean;
  isFeatured: boolean;
  tags: MenuTag[];
  sortOrder: number;
  categorySlug: string;
};

export type MenuCategory = {
  slug: string;
  name: string;
  description?: string;
  sortOrder: number;
  items: MenuItem[];
};

export type MenuSettingsData = {
  pageTitle: string;
  introText?: string;
  currency: string;
  showUnavailableItems: boolean;
  qrTargetUrl?: string;
};

export const defaultMenuSettings: MenuSettingsData = {
  pageTitle: "Danyame Menu",
  introText: "Food, drinks, and poolside favourites — updated daily.",
  currency: "GH₵",
  showUnavailableItems: false,
};

export const staticMenuCategories: MenuCategory[] = [
  {
    slug: "sauces",
    name: "Sauces",
    sortOrder: 0,
    items: [
      {
        slug: "beef-sauce",
        name: "Beef Sauce",
        description: "Shredded beef stir-fry with vegetables, dark soy sauce, seasoned with ginger, garlic and red pepper",
        price: 150,
        isAvailable: true,
        isFeatured: true,
        tags: ["popular"],
        sortOrder: 0,
        categorySlug: "sauces",
      },
      {
        slug: "supreme-sauce",
        name: "Supreme Sauce",
        description: "Shredded chicken stir-fry with vegetables, dark soy sauce, seasoned with ginger and red pepper",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "sauces",
      },
      {
        slug: "seasoned-fish-sauce",
        name: "Seasoned Sauce / Fish Sauce",
        description: "Stir-fry seafood/fish with diced vegetable, dark soy sauce with ginger and garlic",
        price: 200,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "sauces",
      },
    ],
  },
  {
    slug: "snacks",
    name: "Snacks",
    sortOrder: 1,
    items: [
      {
        slug: "meat-pie",
        name: "Meat Pie",
        description: "Minced beef, colorful vegetables, short crust, seasons",
        price: "10.00, 20.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "snacks",
      },
      {
        slug: "sausage-roll",
        name: "Sausage Roll",
        description: "Short crust, sausage",
        price: 10,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "snacks",
      },
      {
        slug: "quiche-lorren",
        name: "Quiche Lorren",
        description: "Short crust, minced beef, tossed with colorful vegetable",
        price: "20.00 - 100.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "snacks",
      },
      {
        slug: "baked-chips",
        name: "Baked Chips",
        description: "Short crust cut into chips length / Short bread biscuit / Pipe biscuit",
        price: "20.00 - 100.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "snacks",
      },
    ],
  },
  {
    slug: "dessert",
    name: "Dessert",
    sortOrder: 2,
    items: [
      {
        slug: "cupcake-plain",
        name: "Cupcake",
        description: "Not decorated",
        price: "10.00, 20.00",
        image: "/assets/menu/items/dessert-cupcake-plain.jpg",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "dessert",
      },
      {
        slug: "cupcake-decorated",
        name: "Cupcake",
        description: "Cake butter topped with buttercream and pringles",
        price: 150,
        image: "/assets/menu/items/dessert-cupcake-decorated.jpg",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "dessert",
      },
      {
        slug: "drv-cake",
        name: "DRV Cake",
        description: "Not decorated",
        price: "30.00, 50.00",
        image: "/assets/menu/items/dessert-drv-cake.jpg",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "dessert",
      },
      {
        slug: "birthday-cake",
        name: "Birthday Cake",
        description: "Cake butter, decorated with butter cream and fondant with some touches",
        price: "150.00 - 1,200.00",
        image: "/assets/menu/items/dessert-birthday-cake.jpg",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "dessert",
      },
      {
        slug: "pan-cake",
        name: "Pan Cake",
        description: "With vanilla ice-cream",
        price: 50,
        image: "/assets/menu/items/dessert-pancake.jpg",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 4,
        categorySlug: "dessert",
      },
      {
        slug: "chocolate-cake",
        name: "Chocolate Cake",
        description: "Sliced top with strawberry",
        price: 150,
        image: "/assets/menu/items/dessert-chocolate-cake.jpg",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 5,
        categorySlug: "dessert",
      },
      {
        slug: "assorted-fruit",
        name: "Assorted Fruit",
        description: "Slices top with honey",
        price: 100,
        image: "/assets/menu/items/dessert-assorted-fruit.jpg",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 6,
        categorySlug: "dessert",
      },
    ],
  },
  {
    slug: "with-a-twist",
    name: "With A Twist",
    sortOrder: 3,
    items: [
      {
        slug: "crispy-chicken-basket",
        name: "Crispy Chicken Basket",
        description: "Well-seasoned chicken coated in butter, served with french fries/yam chips",
        price: "70.00, 100.00",
        isAvailable: true,
        isFeatured: true,
        tags: ["popular"],
        sortOrder: 0,
        categorySlug: "with-a-twist",
      },
      {
        slug: "loaded-fries",
        name: "Loaded Fries",
        description: "Crispy chicken fingers and vegetable on a bed of french fries, top with cheese, sauce",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "with-a-twist",
      },
      {
        slug: "crispy-fingers-platter",
        name: "Crispy Fingers Platter",
        description: "Coated fish strips fried and served with french fries or yam chips",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "with-a-twist",
      },
      {
        slug: "grilled-fillet-plate",
        name: "Grilled Fillet Plate",
        description: "Boneless leg of chicken serve with sautee garlic potato with vegetables",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "with-a-twist",
      },
      {
        slug: "gizzard-pepper-steak",
        name: "Gizzard Pepper Steak",
        description: "Hot spiced gizzard tossed with vegetable serve with yam chips",
        price: 70,
        isAvailable: true,
        isFeatured: false,
        tags: ["spicy"],
        sortOrder: 4,
        categorySlug: "with-a-twist",
      },
    ],
  },
  {
    slug: "pan-and-grill",
    name: "Pan And Grill",
    sortOrder: 4,
    items: [
      {
        slug: "spicy-turkey-wings",
        name: "Spicy Turkey Wings",
        description: "Grilled turkey wings well-seasoned tossed with vegetables",
        price: 70,
        isAvailable: true,
        isFeatured: false,
        tags: ["spicy"],
        sortOrder: 0,
        categorySlug: "pan-and-grill",
      },
      {
        slug: "pan-fried-chicken-wings",
        name: "Pan-Fried Chicken Wings",
        description: "Hot seasoned chicken wings / chops pan grill with sautee vegetables",
        price: 70,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "pan-and-grill",
      },
      {
        slug: "grilled-chicken-leg",
        name: "Grilled Chicken Leg",
        description: "Bone in chicken leg",
        price: 70,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "pan-and-grill",
      },
      {
        slug: "seafood-platter",
        name: "Seafood Platter",
        description: "Shrimps, octopus, squid, prawns sautee with vegetables",
        price: 80,
        isAvailable: true,
        isFeatured: true,
        tags: [],
        sortOrder: 3,
        categorySlug: "pan-and-grill",
      },
    ],
  },
  {
    slug: "salads",
    name: "Salads",
    sortOrder: 5,
    items: [
      {
        slug: "garden-salad",
        name: "Garden Salad",
        description: "Lettuce, carrot, cucumber, onion, vinaigrette/cream, tomato, sweet corn, green pepper",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 0,
        categorySlug: "salads",
      },
      {
        slug: "ghanaian-salad-mix",
        name: "Ghanaian Salad Mix",
        description: "Lettuce, carrot, cucumber, onion, tomato, cream, tuna, egg, sweet corn",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "salads",
      },
      {
        slug: "tuna-pasta-salad",
        name: "Tuna Pasta Salad",
        description: "Tuna, pasta, carrot, onion, cucumber, cream, seasons",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "salads",
      },
      {
        slug: "apple-coleslaw",
        name: "Apple Coleslaw",
        description: "Shredded carrot, shredded cabbage, onion, apple slice",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 3,
        categorySlug: "salads",
      },
    ],
  },
  {
    slug: "sides",
    name: "Sides",
    sortOrder: 6,
    items: [
      {
        slug: "egg-fried-rice",
        name: "Egg Fried Rice",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "sides",
      },
      {
        slug: "egg-sausage-fried-rice",
        name: "Egg and Sausage Fried Rice",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "sides",
      },
      {
        slug: "egg-gizzard-fried-rice",
        name: "Egg and Gizzard Fried Rice",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "sides",
      },
      {
        slug: "gizzard-jollof",
        name: "Gizzard Jollof",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "sides",
      },
      {
        slug: "sausage-jollof",
        name: "Sausage Jollof",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 4,
        categorySlug: "sides",
      },
      {
        slug: "egg-crumbles-jollof",
        name: "Egg Crumbles with Jollof",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 5,
        categorySlug: "sides",
      },
    ],
  },
  {
    slug: "pizza",
    name: "Pizza",
    sortOrder: 7,
    items: [
      {
        slug: "3-season-pizza",
        name: "3 Season Pizza",
        description: "Beef, chicken, sausage, vegetable and cheese, thin crust",
        price: "100.00 - 200.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "pizza",
      },
      {
        slug: "beef-mushroom-pizza",
        name: "Beef & Mushroom",
        description: "Thin crust with beef and mushroom, sauce, vegetable, and cheese",
        price: "100.00 - 200.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "pizza",
      },
      {
        slug: "tuna-pizza",
        name: "Tuna Pizza",
        description: "Thin crust, spread with sauce, top with tuna chunk, vegetables and cheese",
        price: "100.00 - 200.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "pizza",
      },
      {
        slug: "danyame-ultimate",
        name: "Danyame Ultimate",
        description: "Thin crust spread with sauce, top with beef, chicken, sausage, tuna, vegetable, cheese",
        price: 200,
        isAvailable: true,
        isFeatured: true,
        tags: ["popular"],
        sortOrder: 3,
        categorySlug: "pizza",
      },
      {
        slug: "nyame-one-special",
        name: "Nyame One Special",
        description: "Pizza sauce, mozzarella cheese, chicken, beef, tuna, bacon, pepperoni, mushroom, sweet corn, black olives, sausage, green pepper, onion, oregano, barbecue sauce",
        price: "170.00 - 230.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 4,
        categorySlug: "pizza",
      },
      {
        slug: "hawaiian-pizza",
        name: "Hawaiian",
        description: "Pizza sauce, mozzarella cheese, pineapple, bacon, onion, oregano",
        price: "140.00 - 200.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 5,
        categorySlug: "pizza",
      },
      {
        slug: "super-delight-pizza",
        name: "Super Delight Pizza",
        description: "Pizza sauce, beef, spicy chicken, onion, tuna, green pepper, oregano, barbecue sauce, mozzarella cheese",
        price: "130.00 - 180.00",
        isAvailable: true,
        isFeatured: false,
        tags: ["spicy"],
        sortOrder: 6,
        categorySlug: "pizza",
      },
      {
        slug: "pepperoni-pizza",
        name: "Pepperoni Pizza",
        description: "Pizza sauce, mozzarella cheese, mushroom, black olives, onion, green pepper, sweet corn, oregano",
        price: "120.00 - 170.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 7,
        categorySlug: "pizza",
      },
      {
        slug: "veggie-pizza",
        name: "Veggie Pizza",
        description: "Pizza sauce, mozzarella cheese, mushroom, black olives, onion, green pepper, sweet corn, oregano",
        price: "100.00 - 150.00",
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 8,
        categorySlug: "pizza",
      },
      {
        slug: "ritas-special-pizza",
        name: "Rita's Special Pizza",
        description: "Pizza sauce, mozzarella cheese, special beef, sweet corn, onion, green pepper, oregano",
        price: "120.00 - 170.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 9,
        categorySlug: "pizza",
      },
      {
        slug: "lover-pizza",
        name: "Lover Pizza",
        description: "Pizza sauce, beef, chicken, sausage, bacon, tuna, green pepper, onion, oregano, mozzarella cheese, bbq",
        price: "140.00 - 200.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 10,
        categorySlug: "pizza",
      },
      {
        slug: "cheese-pizza",
        name: "Cheese Pizza",
        description: "Pizza sauce, mozzarella cheese, oregano",
        price: "100.00 - 150.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 11,
        categorySlug: "pizza",
      },
      {
        slug: "spicy-chicken-pizza",
        name: "Spicy Chicken Pizza",
        description: "Pizza sauce, mozzarella cheese, spicy chicken, onion, green pepper, oregano",
        price: "110.00 - 160.00",
        isAvailable: true,
        isFeatured: false,
        tags: ["spicy"],
        sortOrder: 12,
        categorySlug: "pizza",
      },
    ],
  },
  {
    slug: "house-special",
    name: "House Special",
    sortOrder: 8,
    items: [
      {
        slug: "omelet-braised-rice",
        name: "Omelet with Braised Rice",
        description: "Vegetable omelet serves with braised rice and sardine and hot pepper/green chili (Angwa mo)",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "house-special",
      },
      {
        slug: "seafood-fried-rice",
        name: "Seafood Fried Rice",
        description: "Shrimps and octopus stir-fry with fried rice",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "house-special",
      },
      {
        slug: "beef-samosa",
        name: "Beef Samosa",
        description: "Minced beef, onion, local spices, garam masala, carrot, spring onion and wrapped",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "house-special",
      },
      {
        slug: "vegetable-spring-rolls",
        name: "Vegetable Spring Rolls",
        description: "Colorful vegetable shredded, local spices, garam masala, thin wrap",
        price: 20,
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 3,
        categorySlug: "house-special",
      },
      {
        slug: "tuna-fish-cake",
        name: "Tuna Fish Cake",
        description: "Tuna, egg, onion, potato, seasons, mix all together",
        price: 30,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 4,
        categorySlug: "house-special",
      },
      {
        slug: "ghanaian-soup-of-the-week",
        name: "Ghanaian Soup of the Week",
        description: "Please ask the waitress/waiter the soup of the week",
        price: 80,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 5,
        categorySlug: "house-special",
      },
    ],
  },
  {
    slug: "vegan-corner",
    name: "Vegan Corner",
    sortOrder: 9,
    items: [
      {
        slug: "veg-fried-rice",
        name: "VEG",
        description: "Mushroom and egg fried rice with vegetable addition",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 0,
        categorySlug: "vegan-corner",
      },
      {
        slug: "vegetarian-pizza",
        name: "Vegetarian Pizza",
        description: "Thin crust, spread with sauce, topped with tossed vegetables and mushroom finished with cheese",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 1,
        categorySlug: "vegan-corner",
      },
      {
        slug: "mushroom-spaghetti",
        name: "Mushroom Spaghetti",
        description: "Spaghetti stir-fry with mushroom and vegetable julienne top with cheese",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 2,
        categorySlug: "vegan-corner",
      },
    ],
  },
  {
    slug: "wrap-and-sandwich",
    name: "Wrap And Sandwich",
    description: "NB: All served with free french fries",
    sortOrder: 10,
    items: [
      {
        slug: "seasonal-sandwich",
        name: "Seasonal Sandwich",
        description: "Tuna fish, avocado, cream, onions, lettuce, fresh bread",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "wrap-and-sandwich",
      },
      {
        slug: "club-sandwich",
        name: "Club Sandwich",
        description: "Fresh bread, chicken, eggs, bacon, tomato, cucumber, lettuce, sauce",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "wrap-and-sandwich",
      },
      {
        slug: "combo-burger",
        name: "Combo Burger",
        description: "Minced beef, seasons, onions, lettuce, cucumber, cheese, slice",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "wrap-and-sandwich",
      },
      {
        slug: "chicken-sharwama",
        name: "Chicken Sharwama",
        description: "Chicken strips, wrap, sharwama sauce, choice of vegetables (cucumber, onion, lettuce, tomato)",
        price: "50.00 - 100.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "wrap-and-sandwich",
      },
      {
        slug: "dddb",
        name: "DDDB",
        description: "Danyame double decker burger; beef, chicken, lettuce, cheese, tomato, pickle, cucumber, sauce, caramelised onion",
        price: "100.00, 120.00",
        isAvailable: true,
        isFeatured: true,
        tags: ["popular"],
        sortOrder: 4,
        categorySlug: "wrap-and-sandwich",
      },
    ],
  },
  {
    slug: "spag-and-pas",
    name: "Spag And Pas",
    sortOrder: 11,
    items: [
      {
        slug: "spaghetti-bolognaise",
        name: "Spaghetti Bolognaise",
        description: "Rich minced beef in tomato sauce, served on spaghettini, top with cheese and aromatic herbs",
        price: "50.00 - 150.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "spag-and-pas",
      },
      {
        slug: "seafood-stir-fry-pasta",
        name: "Seafood Stir-fry",
        description: "Shrimps, octopus, colorful vegetable, seasons, spaghettini aromatic herbs",
        price: "50.00 - 150.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "spag-and-pas",
      },
      {
        slug: "lasagna",
        name: "Lasagna",
        description: "Rich bolognaise sauce, lasagna sheet, cheese",
        price: "100.00, 150.00",
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "spag-and-pas",
      },
    ],
  },
  {
    slug: "drv-dishes",
    name: "DRV Dishes",
    sortOrder: 12,
    items: [
      {
        slug: "grilled-chicken-veggies",
        name: "Grilled Chicken with Veggies",
        description: "Chicken grilled and serve with vegetable rice and tomato sauce / gravy",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "drv-dishes",
      },
      {
        slug: "mixed-rice",
        name: "Mixed Rice",
        description: "Jollof/fried rice mixed with chicken, gizzard and sausage",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "drv-dishes",
      },
      {
        slug: "assorted-jollof",
        name: "Assorted Jollof",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "drv-dishes",
      },
      {
        slug: "fried-rice",
        name: "Fried Rice",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "drv-dishes",
      },
    ],
  },
  {
    slug: "local-dishes",
    name: "Local Dishes",
    sortOrder: 13,
    items: [
      {
        slug: "gob3",
        name: "GOB3",
        description: "Plantain, beans, egg, drumstick, gari",
        price: 80,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "local-dishes",
      },
      {
        slug: "acheke",
        name: "Acheke",
        description: "Tilapia, red fish, chicken",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "local-dishes",
      },
      {
        slug: "vegetable-stew",
        name: "Vegetable Stew",
        description: "Served with steamed rice or boiled yam / plantain",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: ["vegetarian"],
        sortOrder: 2,
        categorySlug: "local-dishes",
      },
      {
        slug: "sundays-omotuo",
        name: "Sundays Omotuo",
        description: "Ovals, salmon, goat, beef",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "local-dishes",
      },
      {
        slug: "goat-jollof",
        name: "Goat Jollof",
        description: "Spicy goat meat, serve with jollof rice, shito and salad",
        price: 120,
        isAvailable: true,
        isFeatured: true,
        tags: ["popular", "spicy"],
        sortOrder: 4,
        categorySlug: "local-dishes",
      },
      {
        slug: "banku-tilapia",
        name: "Banku & Tilapia",
        description: "Well-seasoned tilapia, serve with banku and vegetable, hot shito/chilli",
        price: 150,
        isAvailable: true,
        isFeatured: true,
        tags: ["popular", "spicy"],
        sortOrder: 5,
        categorySlug: "local-dishes",
      },
      {
        slug: "ampesi-i",
        name: "Ampesi (I)",
        description: "Yam, plantain, cocoyam, garden eggs, egg, fish, kako",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 6,
        categorySlug: "local-dishes",
      },
      {
        slug: "ampesi-ii",
        name: "Ampesi (II)",
        description: "Kontomire, palava sauce, egg, fish, kako",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 7,
        categorySlug: "local-dishes",
      },
      {
        slug: "ampesi-iii",
        name: "Ampesi (III)",
        description: "Vegetable stew, egg, chicken, fish",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 8,
        categorySlug: "local-dishes",
      },
      {
        slug: "ampesi-iv",
        name: "Ampesi (IV)",
        description: "Gravy, egg, chicken, fish",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 9,
        categorySlug: "local-dishes",
      },
      {
        slug: "ampesi-v",
        name: "Ampesi (V)",
        description: "Abom",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 10,
        categorySlug: "local-dishes",
      },
      {
        slug: "banku-okro",
        name: "Banku with Okro",
        description: "Okro stew-wele, crab, tuna, meat, kako, offal",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 11,
        categorySlug: "local-dishes",
      },
      {
        slug: "omo-tuo",
        name: "Omo Tuo",
        description: "Groundnut soup, palmnut soup",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 12,
        categorySlug: "local-dishes",
      },
      {
        slug: "tuo-zaafi",
        name: "Tuo Zaafi",
        description: "Kuuka, stew, beef, wele, offals, fish",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 13,
        categorySlug: "local-dishes",
      },
      {
        slug: "goat-light-soup-rice",
        name: "Goat & Light Soup with Rice",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 14,
        categorySlug: "local-dishes",
      },
      {
        slug: "banku-cassava-fish",
        name: "Banku & Cassava Fish",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 15,
        categorySlug: "local-dishes",
      },
      {
        slug: "banku-red-fish",
        name: "Banku & Red Fish",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 16,
        categorySlug: "local-dishes",
      },
    ],
  },
  {
    slug: "fufu-konkonte",
    name: "Fufu / Konkonte",
    sortOrder: 14,
    items: [
      {
        slug: "fufu-dry-fish",
        name: "With Dry Fish",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 0,
        categorySlug: "fufu-konkonte",
      },
      {
        slug: "fufu-goat-meat",
        name: "With Goat Meat",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 1,
        categorySlug: "fufu-konkonte",
      },
      {
        slug: "fufu-beef",
        name: "With Beef",
        price: 120,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 2,
        categorySlug: "fufu-konkonte",
      },
      {
        slug: "fufu-chicken",
        name: "With Chicken Meat",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 3,
        categorySlug: "fufu-konkonte",
      },
      {
        slug: "fufu-dry-tilapia",
        name: "With Dry Tilapia",
        price: 150,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 4,
        categorySlug: "fufu-konkonte",
      },
      {
        slug: "fufu-tuna",
        name: "With Tuna",
        price: 80,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 5,
        categorySlug: "fufu-konkonte",
      },
      {
        slug: "fufu-fresh-salmon",
        name: "With Fresh Salmon",
        price: 100,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 6,
        categorySlug: "fufu-konkonte",
      },
      {
        slug: "fufu-snail",
        name: "With Snail",
        price: 50,
        isAvailable: true,
        isFeatured: false,
        tags: [],
        sortOrder: 7,
        categorySlug: "fufu-konkonte",
      },
    ],
  },
  {
    slug: "drinks",
    name: "Drinks",
    sortOrder: 15,
    items: [
      {
        slug: "fresh-coconut",
        name: "Fresh Coconut",
        description: "Chilled whole coconut, cracked to order.",
        price: 20,
        isAvailable: true,
        isFeatured: false,
        tags: ["non-alcoholic"],
        sortOrder: 0,
        categorySlug: "drinks",
      },
      {
        slug: "bottled-water",
        name: "Bottled Water",
        price: 8,
        isAvailable: true,
        isFeatured: false,
        tags: ["non-alcoholic"],
        sortOrder: 1,
        categorySlug: "drinks",
      },
      {
        slug: "danyame-sunset",
        name: "Danyame Sunset",
        description: "Tequila, passion fruit, and citrus.",
        price: 45,
        isAvailable: true,
        isFeatured: true,
        tags: ["alcoholic"],
        sortOrder: 2,
        categorySlug: "drinks",
      },
      {
        slug: "poolside-mojito",
        name: "Poolside Mojito",
        description: "Mint, lime, and white rum.",
        price: 40,
        isAvailable: true,
        isFeatured: false,
        tags: ["alcoholic"],
        sortOrder: 3,
        categorySlug: "drinks",
      },
      {
        slug: "soft-drinks",
        name: "Soft Drinks",
        description: "Assorted chilled soft drinks.",
        price: 15,
        isAvailable: true,
        isFeatured: false,
        tags: ["non-alcoholic"],
        sortOrder: 4,
        categorySlug: "drinks",
      },
    ],
  },
];

export function getStaticFeaturedMenuItems(
  categories: MenuCategory[],
): MenuItem[] {
  return categories
    .flatMap((category) => category.items)
    .filter((item) => item.isFeatured)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function filterMenuItems(
  items: MenuItem[],
  showUnavailableItems: boolean,
): MenuItem[] {
  if (showUnavailableItems) {
    return items;
  }

  return items.filter((item) => item.isAvailable);
}

export function applyMenuVisibility(
  categories: MenuCategory[],
  showUnavailableItems: boolean,
): MenuCategory[] {
  return categories
    .map((category) => ({
      ...category,
      items: filterMenuItems(category.items, showUnavailableItems),
    }))
    .filter((category) => category.items.length > 0);
}

export function formatMenuPrice(price: number | string, currency: string): string {
  if (typeof price === "string") {
    return `${currency}${price}`;
  }
  const formatted = Number.isInteger(price) ? String(price) : price.toFixed(2);
  return `${currency}${formatted}`;
}

export function formatMenuDisplayPrice(price: number | string, currency: string): string {
  return formatMenuPrice(price, currency).replace(/^GH₵/, "GHS ");
}
