/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    'menu-categories': MenuCategory;
    'menu-items': MenuItem;
    'menu-qr': MenuQr;
    'gallery-categories': GalleryCategory;
    'gallery-images': GalleryImage;
    'contact-inquiries': ContactInquiry;
    'newsletter-subscribers': NewsletterSubscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'menu-qr': MenuQrSelect<false> | MenuQrSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'experiences-page': ExperiencesPage;
    'about-page': AboutPage;
    'gallery-page': GalleryPage;
    'events-hub-page': EventsHubPage;
    'host-event-page': HostEventPage;
    'contact-page': ContactPage;
    'menu-settings': MenuSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'experiences-page': ExperiencesPageSelect<false> | ExperiencesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'events-hub-page': EventsHubPageSelect<false> | EventsHubPageSelect<true>;
    'host-event-page': HostEventPageSelect<false> | HostEventPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'menu-settings': MenuSettingsSelect<false> | MenuSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Your name as it will appear in the admin panel.
   */
  name?: string | null;
  /**
   * Admins can manage all site content.
   */
  role: 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * The calendar date of the event.
   */
  eventDate: string;
  /**
   * Display time, e.g. "2:00 PM".
   */
  startTime: string;
  location: string;
  shortSummary: string;
  description: string;
  posterImage: number | Media;
  hasTickets?: boolean | null;
  ticketLabel?: string | null;
  /**
   * Optional external ticket link.
   */
  ticketUrl?: string | null;
  /**
   * Only one event can be featured at a time.
   */
  isFeatured?: boolean | null;
  /**
   * Lower numbers appear first within the same date.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  /**
   * Lower numbers appear first on the menu.
   */
  sortOrder?: number | null;
  /**
   * Inactive categories are hidden from the public menu.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category: number | MenuCategory;
  description?: string | null;
  /**
   * Enter price in Ghana cedis.
   */
  price: number;
  image?: (number | null) | Media;
  /**
   * Unavailable items can be hidden on the public menu.
   */
  isAvailable?: boolean | null;
  /**
   * Featured items appear in a highlight section on /menu.
   */
  isFeatured?: boolean | null;
  tags?: ('popular' | 'new' | 'spicy' | 'vegetarian' | 'alcoholic' | 'non-alcoholic')[] | null;
  /**
   * Lower numbers appear first within a category.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Generate and download a QR code that links to your public menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-qr".
 */
export interface MenuQr {
  id: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Lower numbers appear first in the gallery tabs.
   */
  sortOrder?: number | null;
  /**
   * Inactive categories are hidden from the public gallery.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  title: string;
  category: number | GalleryCategory;
  image: number | Media;
  /**
   * Describe the image for accessibility.
   */
  alt: string;
  /**
   * Lower numbers appear first. The gallery layout uses the first 7 images per category.
   */
  sortOrder?: number | null;
  /**
   * Unpublished images are hidden from the public gallery.
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions from the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  email: string;
  phone: string;
  eventType: 'Corporate Event' | 'Birthday / Celebration' | 'Pool Party' | 'Food & Nightlife' | 'Other';
  eventDate: string;
  message: string;
  /**
   * Track follow-up progress for this inquiry.
   */
  status: 'new' | 'contacted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter signups from the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  /**
   * Where the signup came from, e.g. footer or homepage.
   */
  source?: string | null;
  status: 'subscribed' | 'unsubscribed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'menu-qr';
        value: number | MenuQr;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: number | GalleryCategory;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  eventDate?: T;
  startTime?: T;
  location?: T;
  shortSummary?: T;
  description?: T;
  posterImage?: T;
  hasTickets?: T;
  ticketLabel?: T;
  ticketUrl?: T;
  isFeatured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  description?: T;
  price?: T;
  image?: T;
  isAvailable?: T;
  isFeatured?: T;
  tags?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-qr_select".
 */
export interface MenuQrSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  image?: T;
  alt?: T;
  sortOrder?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  eventType?: T;
  eventDate?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroImage?: (number | null) | Media;
  heroHeadline1: string;
  heroHeadline2: string;
  heroHeadline3: string;
  heroTagline: string;
  heroSubtext: string;
  everythingTitle: string;
  everythingBody: string;
  everythingCtaLabel: string;
  everythingCtaHref: string;
  categories?:
    | {
        title: string;
        image: number | Media;
        href: string;
        id?: string | null;
      }[]
    | null;
  aboutTitle: string;
  aboutBody: string;
  aboutImage?: (number | null) | Media;
  aboutImageAlt?: string | null;
  aboutCtaLabel: string;
  aboutCtaHref: string;
  eventsSectionTitle: string;
  /**
   * Use a new line for the line break in the heading.
   */
  eventsHeading: string;
  eventsBody: string;
  eventsMetaEveryWeek: string;
  eventsMetaLocation: string;
  eventsMetaVibes: string;
  eventsRegisterLabel: string;
  eventsRegisterHref: string;
  eventsCountdownLabel: string;
  eventsViewAllLabel: string;
  eventsViewAllHref: string;
  /**
   * When enabled, the countdown uses the featured event date from Events.
   */
  eventsUseCmsCountdown?: boolean | null;
  planningEventImage?: (number | null) | Media;
  planningEventImageAlt?: string | null;
  planningEventTitle: string;
  planningEventBody: string;
  planningEventCtaLabel: string;
  planningEventCtaHref: string;
  galleryTitle: string;
  galleryIntro: string;
  /**
   * When enabled, the first 7 published gallery images are used instead of the manual picks below.
   */
  galleryUseCmsGallery?: boolean | null;
  /**
   * Used when CMS gallery is off. Provide 7 images for the home layout.
   */
  galleryImages?:
    | {
        image: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  galleryCtaLabel: string;
  galleryCtaHref: string;
  testimonialsTitle: string;
  testimonialsBackgroundImage?: (number | null) | Media;
  testimonialsItems?:
    | {
        name: string;
        role: string;
        quote: string;
        image: number | Media;
        imageAlt: string;
        cardStyle: 'light' | 'dark';
        id?: string | null;
      }[]
    | null;
  finalCtaLine1: string;
  finalCtaLine2: string;
  finalCtaLine3: string;
  finalCtaLine4: string;
  finalCtaBody: string;
  finalCtaSecondaryLabel: string;
  finalCtaSecondaryHref: string;
  finalCtaPrimaryLabel: string;
  finalCtaPrimaryHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences-page".
 */
export interface ExperiencesPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle: string;
  taglinePrimary: string;
  taglineSecondary: string;
  categories?:
    | {
        /**
         * URL anchor for this section, e.g. events, pool, food, games.
         */
        slug: string;
        label: string;
        title: string;
        description: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  exploreMoreTitle: string;
  exploreMoreIntro: string;
  exploreMoreItems?:
    | {
        name: string;
        tagline: string;
        /**
         * Preview image shown on hover (desktop).
         */
        image?: (number | null) | Media;
        imageAlt?: string | null;
        href?: string | null;
        /**
         * Main paragraph in the popup.
         */
        description?: string | null;
        /**
         * e.g. Access, Starting From, Capacity.
         */
        detailRows?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        includes?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        primaryCtaLabel?: string | null;
        primaryCtaHref?: string | null;
        secondaryCtaLabel?: string | null;
        secondaryCtaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  finalCtaLine1: string;
  finalCtaLine2: string;
  finalCtaLine3: string;
  finalCtaLine4: string;
  finalCtaBody: string;
  finalCtaSecondaryLabel: string;
  finalCtaSecondaryHref: string;
  finalCtaPrimaryLabel: string;
  finalCtaPrimaryHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroTitle: string;
  heroDescription: string;
  introLabel: string;
  introWelcomeHeading: string;
  introPrimaryImage?: (number | null) | Media;
  introPrimaryImageAlt?: string | null;
  introSinceCardImage?: (number | null) | Media;
  introSinceCardLabel?: string | null;
  introSinceCardText?: string | null;
  introParagraph: string;
  leadershipIntro: string;
  leadershipImage?: (number | null) | Media;
  leadershipImageAlt?: string | null;
  leadershipParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stripImages?:
    | {
        image: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  missionIcon?: (number | null) | Media;
  missionTitle: string;
  missionText: string;
  visionIcon?: (number | null) | Media;
  visionTitle: string;
  visionText: string;
  locationBackgroundImage?: (number | null) | Media;
  locationPinIcon?: (number | null) | Media;
  locationText: string;
  mapTitle: string;
  mapImage?: (number | null) | Media;
  mapLink: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  heroTitle: string;
  heroIntro: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-hub-page".
 */
export interface EventsHubPage {
  id: number;
  heroImage?: (number | null) | Media;
  heroImageAlt?: string | null;
  heroTitle: string;
  heroBody: string;
  heroHostCtaLabel: string;
  heroHostCtaHref: string;
  heroAttendCtaLabel: string;
  heroAttendCtaHref: string;
  sectionTitle: string;
  sectionIntro: string;
  hostCard: {
    image: number | Media;
    imageAlt: string;
    title: string;
    body: string;
    ctaLabel: string;
    ctaHref: string;
  };
  attendCard: {
    image: number | Media;
    imageAlt: string;
    title: string;
    body: string;
    ctaLabel: string;
    ctaHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "host-event-page".
 */
export interface HostEventPage {
  id: number;
  title: string;
  body: string;
  heroImage?: (number | null) | Media;
  heroImageAlt: string;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  headlineLine1: string;
  headlineLine2: string;
  intro: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-settings".
 */
export interface MenuSetting {
  id: number;
  pageTitle: string;
  /**
   * Optional short line shown below the menu title.
   */
  introText?: string | null;
  currency: string;
  /**
   * When enabled, sold-out items still appear but are visibly disabled.
   */
  showUnavailableItems?: boolean | null;
  /**
   * URL encoded in the menu QR code. Usually https://yourdomain.com/menu
   */
  qrTargetUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  shortName: string;
  location: string;
  phone: string;
  phoneHref: string;
  /**
   * Second phone number shown in the footer.
   */
  secondaryPhone?: string | null;
  secondaryPhoneHref?: string | null;
  /**
   * WhatsApp link for the secondary phone number.
   */
  whatsappHref?: string | null;
  whatsappLabel?: string | null;
  email: string;
  /**
   * Opening hours shown in the footer.
   */
  openingHoursRows?:
    | {
        label: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Deprecated. Use Opening Hours rows instead.
   */
  openingHours?: string | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Links shown under Explore Danyame in the footer.
   */
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightYear: number;
  /**
   * Primary logo used on the site.
   */
  logo?: (number | null) | Media;
  /**
   * Optional logo for dark backgrounds.
   */
  logoDark?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroImage?: T;
  heroHeadline1?: T;
  heroHeadline2?: T;
  heroHeadline3?: T;
  heroTagline?: T;
  heroSubtext?: T;
  everythingTitle?: T;
  everythingBody?: T;
  everythingCtaLabel?: T;
  everythingCtaHref?: T;
  categories?:
    | T
    | {
        title?: T;
        image?: T;
        href?: T;
        id?: T;
      };
  aboutTitle?: T;
  aboutBody?: T;
  aboutImage?: T;
  aboutImageAlt?: T;
  aboutCtaLabel?: T;
  aboutCtaHref?: T;
  eventsSectionTitle?: T;
  eventsHeading?: T;
  eventsBody?: T;
  eventsMetaEveryWeek?: T;
  eventsMetaLocation?: T;
  eventsMetaVibes?: T;
  eventsRegisterLabel?: T;
  eventsRegisterHref?: T;
  eventsCountdownLabel?: T;
  eventsViewAllLabel?: T;
  eventsViewAllHref?: T;
  eventsUseCmsCountdown?: T;
  planningEventImage?: T;
  planningEventImageAlt?: T;
  planningEventTitle?: T;
  planningEventBody?: T;
  planningEventCtaLabel?: T;
  planningEventCtaHref?: T;
  galleryTitle?: T;
  galleryIntro?: T;
  galleryUseCmsGallery?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  galleryCtaLabel?: T;
  galleryCtaHref?: T;
  testimonialsTitle?: T;
  testimonialsBackgroundImage?: T;
  testimonialsItems?:
    | T
    | {
        name?: T;
        role?: T;
        quote?: T;
        image?: T;
        imageAlt?: T;
        cardStyle?: T;
        id?: T;
      };
  finalCtaLine1?: T;
  finalCtaLine2?: T;
  finalCtaLine3?: T;
  finalCtaLine4?: T;
  finalCtaBody?: T;
  finalCtaSecondaryLabel?: T;
  finalCtaSecondaryHref?: T;
  finalCtaPrimaryLabel?: T;
  finalCtaPrimaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences-page_select".
 */
export interface ExperiencesPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  taglinePrimary?: T;
  taglineSecondary?: T;
  categories?:
    | T
    | {
        slug?: T;
        label?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  exploreMoreTitle?: T;
  exploreMoreIntro?: T;
  exploreMoreItems?:
    | T
    | {
        name?: T;
        tagline?: T;
        image?: T;
        imageAlt?: T;
        href?: T;
        description?: T;
        detailRows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        includes?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        id?: T;
      };
  finalCtaLine1?: T;
  finalCtaLine2?: T;
  finalCtaLine3?: T;
  finalCtaLine4?: T;
  finalCtaBody?: T;
  finalCtaSecondaryLabel?: T;
  finalCtaSecondaryHref?: T;
  finalCtaPrimaryLabel?: T;
  finalCtaPrimaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  introLabel?: T;
  introWelcomeHeading?: T;
  introPrimaryImage?: T;
  introPrimaryImageAlt?: T;
  introSinceCardImage?: T;
  introSinceCardLabel?: T;
  introSinceCardText?: T;
  introParagraph?: T;
  leadershipIntro?: T;
  leadershipImage?: T;
  leadershipImageAlt?: T;
  leadershipParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stripImages?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  missionIcon?: T;
  missionTitle?: T;
  missionText?: T;
  visionIcon?: T;
  visionTitle?: T;
  visionText?: T;
  locationBackgroundImage?: T;
  locationPinIcon?: T;
  locationText?: T;
  mapTitle?: T;
  mapImage?: T;
  mapLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroIntro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-hub-page_select".
 */
export interface EventsHubPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroImageAlt?: T;
  heroTitle?: T;
  heroBody?: T;
  heroHostCtaLabel?: T;
  heroHostCtaHref?: T;
  heroAttendCtaLabel?: T;
  heroAttendCtaHref?: T;
  sectionTitle?: T;
  sectionIntro?: T;
  hostCard?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  attendCard?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "host-event-page_select".
 */
export interface HostEventPageSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  heroImage?: T;
  heroImageAlt?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  headlineLine1?: T;
  headlineLine2?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-settings_select".
 */
export interface MenuSettingsSelect<T extends boolean = true> {
  pageTitle?: T;
  introText?: T;
  currency?: T;
  showUnavailableItems?: T;
  qrTargetUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  location?: T;
  phone?: T;
  phoneHref?: T;
  secondaryPhone?: T;
  secondaryPhoneHref?: T;
  whatsappHref?: T;
  whatsappLabel?: T;
  email?: T;
  openingHoursRows?:
    | T
    | {
        label?: T;
        hours?: T;
        id?: T;
      };
  openingHours?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightYear?: T;
  logo?: T;
  logoDark?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}